name: run main.py

on:
  schedule:
    - cron: '0 22 * * *'

jobs:
  run-python-script:
    name: Run Python Script and Push Changes
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9 '

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python Script
      run: python main.py 
    
    - name: Add and Commit Changes
      run: |
        git add .
        git config --global user.email "actions@example.com"
        git config --global user.name "GitHub Actions"
        git commit -m "Update files via GitHub Actions"
    
    - name: Push Changes
      run: git push origin main  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 